FROM python:3.13-alpine

WORKDIR /app

RUN apk update \
    && apk add --no-cache \
        build-base \
    && rm -rf /var/cache/apk/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
