FROM python:3.13-alpine

WORKDIR /app

# Install system dependencies
RUN apk update \
    && apk add --no-cache \
        curl \
    && rm -rf /var/cache/apk/*

# Copy Python dependencies file
COPY requirements.txt ./

# Install Python dependencies
RUN pip install --no-cache-dir -r ./requirements.txt

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONPATH=/app

# Run tests by default
CMD ["pytest", "-v"]
