server {
    listen       80 default_server;
    listen       [::]:80 default_server;
    server_name  _;  # Обслуживает любой хост

    location @backend {
        proxy_pass http://django-admin:8000;
    }

    location /admin/ {
        proxy_pass http://django-admin:8000;
    }

    location ^~ /static/ {
        alias /var/www/static/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000, must-revalidate";
    }

    location ^~ /api/ {
        proxy_pass http://django-admin:8000;
    }

    location / {
        try_files $uri @backend;
    }

    error_page  404              /404.html;
}